Cache definitions
Altinn/app-lib-dotnet pull request #101
Opened 2022-12-01 07:51 UTC by HenningNormann

## Description
Avoid reading process definition from file for each invocation

## Related Issue(s)
- #{93} in the platform team

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2022-12-02 07:52 UTC, tjololo requested changes
Please have a look at the codeQL error

2022-12-02 07:52 UTC, tjololo commented on src/Altinn.App.Core/Internal/Process/ProcessReader.cs
> +        }
Please fix this error

2022-12-05 11:11 UTC, tjololo commented
@HenningNormann is there any reason you are choosing static fields over MemoryCache?

2022-12-05 13:16 UTC, HenningNormann commented
> 



> @HenningNormann is there any reason you are choosing static fields over MemoryCache?

@tjololo To avoid changing a lot of interfaces to transfer the cache from a DI constructor to ProcessReader and because the value should be cached for the lifetime of the pod - without the need for any cache configuration.

2022-12-21 09:10 UTC, tjololo commented
Has the time it takes to read this from the filesystem in a docker container been identified as a critical issue? We should not consume more memory than necessary. All applications in a cluster consume memory from the same pool and we should make sure that inactive apps don't consume more than necessary to ensure that apps that are receiving load have as much as possible resources available.

2022-12-22 08:00 UTC, HenningNormann commented
> 

Yes, it has been identified as a significant resource consumer. The memory size of the cached object looks very small to me.

2023-01-09 08:31 UTC, tjololo commented
Getting some fresh eyes on this after the holiday I think a simpler and better solution would be to leave the ProcessReader implementation as is and register it with the dependency injection as a singleton. I think this should yield the same performance boost as this solution, but free us from handling dirtyreads with locking in our code. Have a look at [ServiceCollectionExtension line 219](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Extensions/ServiceCollectionExtensions.cs#L219)

2023-01-12 07:42 UTC, HenningNormann commented
> Getting some fresh eyes on this after the holiday I think a simpler and better solution would be to leave the ProcessReader implementation as is and register it with the dependency injection as a singleton. I think this should yield the same performance boost as this solution, but free us from handling dirtyreads with locking in our code. Have a look at [ServiceCollectionExtension line 219](https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Extensions/ServiceCollectionExtensions.cs#L219)

Have changed as suggested

2023-01-12 07:45 UTC, tjololo approved these changes
:godmode:

2023-01-12 07:50 UTC, merged

2023-01-12 07:51 UTC, tjololo commented
I will release a preview version (7.2.1-preview.1) so you can test that the changes have the desired affect