Remove `Scrutor` as dependency, refactor `ProfileClient`
Altinn/app-lib-dotnet pull request #666
Opened 2024-05-30 20:14 UTC by martinothamar

## Description
In #589 we migrated the protobuf-net metrics that were used in service decorators to use `System.Diagnostics` stuff in `Telemetry`. So now there was only cache decorator for `ProfileClient` left. This PR moves caching inside the client and removed the package dep

## Related Issue(s)
- N/A

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-05-30 20:16 UTC, martinothamar commented
P.S. could not find any usage of Scrutor API from search across apps

2024-05-31 03:37 UTC, ivarne requested changes
I think there is a difference in the implementation here.

2024-05-31 03:37 UTC, ivarne commented on src/Altinn.App.Core/Infrastructure/Clients/Profile/ProfileClient.cs
The old code gets the memory cache from DI.

Won't this approach disable the cache in an app when the service is registered with `.AddHttpClient<>`?

2024-05-31 03:37 UTC, ivarne commented on test/Altinn.App.Core.Tests/Infrastructure/Clients/Profile/ProfileClientTests.cs
> +        var profile2 = await client.GetUserProfile(userId);
Resolve the client from different scopes to ensure that it caches across scopes.

2024-05-31 05:48 UTC, martinothamar commented
True, there were breaking changes as well, since those types are public... Went with a different approach

2024-05-31 11:12 UTC, HauklandJ approved these changes

2024-05-31 11:34 UTC, ivarne approved these changes

2024-05-31 11:36 UTC, ivarne commented
I don't think we need to have stable dependencies in DI constructors, but this is a fine solution.

2024-05-31 12:09 UTC, merged